#!/usr/bin/env bash
set -e

ag -s 'Fprintf.*os.Stderr' \
  --ignore-dir vendor \
  --ignore-dir tools \
  --color \
  | ag -v 'ansirefresh ticker: write error:' \
  | ag -v 'stderr:' \
  | ag -v 'mincopies: copier error:' \
  | ag -v 'multireader: copier error:'
