#!/usr/bin/env ruby

VERSION_PATH = "cmd/VERSION"
GEN_PACKAGE = "./cmd"

def release
  # ensure clean index
  log "checking if index is clean"
  if system "git status --porcelain | grep -v '^??' -q"
    raise "dirty index"
  end

  # current version
  ver = File.read(VERSION_PATH, encoding: Encoding::UTF_8).chomp
  ver =~ /\A\d+\z/ or raise "invalid format in %s" % VERSION_PATH
  log "current version: %s" % ver

  # tag
  tag = "v%s" % ver
  log "new tag: %s" % tag
  system "git", "tag", tag \
    or raise "`git tag` failed"

  # new version
  ver = "%d" % (ver.to_i + 1)
  log "new version: %s" % ver
  File.write(VERSION_PATH, "%s\n" % ver)

  # generate version.go
  system "go", "generate", GEN_PACKAGE \
    or raise "`go generate` failed"

  # commit
  log "committing"
  system "git", "commit", "-e", "-v", "-m", "starting v%s" % ver,
    VERSION_PATH,
    GEN_PACKAGE \
      or raise "`git commit` failed"
end

def log(msg)
  $stdout.puts msg
end

release
